kind: ReplicaSet

apiVersion: apps/v1

metadata:
  name: bar-app
  #namespace: apps
  labels:
    app: bar

spec:
  replicas: 3
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - image: registry.k8s.io/e2e-test-images/agnhost:2.39
        name: bar-app
        command:
        - /agnhost
        - serve-hostname
        - --http=true
        - --port=8080

---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
  #namespace: apps
spec:
  selector:
    app: bar
  ports:
  - port: 8080
