kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: bar-app
  #namespace: apps
  labels:
    app: bar
spec:
  replicas: 3
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --http=true
    - --port=8080
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
    name: bar-app

---

kind: Service
apiVersion: v1
metadata:
  name: bar-service
  #namespace: apps
spec:
  selector:
    app: bar
  ports:
  # Default port used by the image
  - port: 8080
