# obrigatório para o chart
publicURL: "https://jitsi.127.0.0.1.nip.io"

jvb:
  useHostPort: true
  useNodeIP: true

web:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: jitsi.127.0.0.1.nip.io
        paths:
          - /
    tls:
      - secretName: https-certs
        hosts:
          - jitsi.127.0.0.1.nip.io

jibri:
  ## Enabling Jibri will allow users to record
  ## and/or stream their meetings (e.g. to YouTube).
  enabled: true

  ## Enable single-use mode for Jibri (recommended).
  singleUseMode: false

  ## Enable multiple Jibri instances.
  ## Secommended for single-use mode.
  replicaCount: 1

  ## Enable recording service.
  ## Set this to true/false to enable/disable local recordings.
  ## Defaults to enabled (allow local recordings).
  recording: true

  ## Enable livestreaming service.
  ## Set this to true/false to enable/disable live streams.
  ## Defaults to disabled (livestreaming is forbidden).
  livestreaming: true

  ## Enable persistent storage for local recordings.
  ## If disabled, jibri pod will use a transient
  ## emptyDir-backed storage instead.
  persistence:
    enabled: true
    size: 32Gi

  shm:
    ## Set to true to enable "/dev/shm" mount.
    ## May be required by built-in Chromium.
    enabled: true

